sudo: required
services:
    - docker

before_install:
    - docker build -t esaputra/docker-react -f Dockerfile.dev .

scripts:
    - docker run -e CI=true esaputra/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-west-2-612279425882"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
        secure: "$AWS_SECRET_KEY"